### ISSUE TITLE
class & function 'UW_Media_Credit'

### ISSUE THREAD

**Issue by morgan-lang** [uweb/uw-2014#100]
Not a showstopper by any means, but something you might want to be aware of. I just installed uw-2014 and created a child theme from it. I get this warning whenever I create or edit a post or page:

```Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'UW_Media_Credit' does not have a method 'add_media_credit_shortcode_to_tinymce' in /nfs/bronfs/uwfs/hw00/d43/uwmpaf/wp-includes/class-wp-hook.php on line 286```

Grepping 'add_media_credit_shortcode_to_tinymce' brought me to wp-content/themes/uw-2014/setup/class.uw-media-credit.php, line 12:

```add_filter( 'mce_external_plugins', array( $this, 'add_media_credit_shortcode_to_tinymce' ) );```

**Comment by cseto** [comment]
I'm trying out the theme as well and noticed this warning. I had installed the theme a week ago and don't remember seeing this warning until continuing to explore the theme this week.

**Comment by lcaple** [comment]
Tracked the bug down to a function that was removed in the last release.

If you grab the latest update it will fix the PHP error.

**Comment by morgan-lang** [comment]
That's great. Thanks for following up.
