### ISSUE TITLE
Request for compatibility with Github Updater plugin.

### ISSUE THREAD

**Issue by jbleys** [uweb/uw-2014#116]
Hi,

I use the [Github Updater](https://github.com/afragen/github-updater) plugin extensively to manage updates for themes and plugins that do not reside on wordpress.com.

Would it be possible to make the UW Theme (and possibly the various UW plugins) compatible with the Github Updater plugin? 

In essence this means that the theme's style.css header needs to be updated with an additional declaration. See [Github Updater usage](https://github.com/afragen/github-updater/wiki/Usage). A site administrator will then be able to update the theme through the site's dashboard interface, as long as proper theme versioning is maintained.

Thanks for your consideration and kind regards,

Jasper Bleijs
Department of Global Health, University of Washington

**Comment by lcaple** [comment]
Hi Jasper,

This is a fantastic idea. This is definitely something I am going to add to my plan for the next major release! I appreciate the links as well.

--Lauren

**Comment by lcaple** [comment]
Hi Jasper, thanks for your patience. Your specific request for compatibility with GitHub updater was addressed in 512f34de59210ce66550db4eca019fb343eb96bd, and we have plans to look into building in a Github-based theme updater as well.
