### ISSUE TITLE
CSS Issue with long links in footer

### ISSUE THREAD

**Issue by BonPacific** [uweb/uw-2014#117]
On mobile devices running Chrome, extremely long text on links inside `<ul class="footer-links">` will begin to overlap with the '/' divider. Issue can be seen on admit.washington.edu, or any other UW-2014 site if the link text is long enough. 

This affects links larger than ~40 characters, depending on the  specific text.

**Comment by lcaple** [comment]
@BonPacific Thanks for the example and bug report. Was able to reproduce this on multiple browsers with narrow widths. Seems the be an issue with CSS placement of the slashes.

**Comment by lcaple** [comment]
@BonPacific We just fixed this in #118. If you grab the most recent copy of master you should no longer see this bug.
