### ISSUE TITLE
Quicklinks "distort" when using tab function in IE 1

### ISSUE THREAD

**Issue by NemesisVex** [uweb/uw-2014#12]
Hello.

One of our testers noticed this problem with the theme in IE 11. I'll just copy and paste the bug we have in our tracking system here as is. I did notice that repro step no. 4 has been fixed on the home page since the original bug was filed, so we'll need to pull those changes into our theme. Repro step no. 5 still seems to be a problem on the home page but oddly enough not on the [research site] (http://www.washington.edu/research/).

## Description

Keyboard Navigation in IE 11 causes Search icon and Quick Links label to display incorrectly.

## Impact

User sees the incorrect icon and shifted text until they open a new page. Once a new page is opened the icon and Quick Link text revert to the correct format.

## Repro Steps

1. While using IE 11, open http://www.washington.edu/research/
2. Click on the purple banner to set the focus
3. Tab to move the focus through the navigation until the "Search" icon is selected
4. Tab once more to move away from the search option. <strike>User will see distorted search icon.</strike> *(This looks like it's been fixed.)*
5. Tab two more times through Quick Links. User will see distorted Quick Links label

## Expected Results

Search icon and Quick Links label should display normally throughout the user's experience and should not display as distorted.

## Actual Results

Search icon and Quick Links label display distorted until user refreshes page or navigates to a new page.

![search and quick links label error](https://cloud.githubusercontent.com/assets/464423/9041900/c57624d8-39bf-11e5-8577-57d3efd52263.png)

**Comment by kilianf** [comment]
This should now be fixed. The search icon had a "focusable='false'" on the SVG, which the Quick Links SVG didn't have, and they now both have that attribute.

Thanks!
