### ISSUE TITLE
Problems with keyboard focus when exiting search

### ISSUE THREAD

**Issue by terrill** [uweb/uw-2014#14]
Keyboard users can open search by pressing enter or space when the search icon has focus. When the search field appears their focus is placed in that field, and if they press escape their focus is returned to the original icon. This is all perfect. However, if instead of pressing Escape they press Tab (with or without entering a search term), their focus deviates from what's expected: 

1. On pages with search-related radio buttons, they seem to land on the radio buttons. However, there's no visual indication that this has happened. Initially I was unclear where focus had gone, and discovered it was on the radio buttons by using the up/down arrows to change the selected radio button. 

2. On pages with no radio buttons (e.g., the home page) pressing tab from the search field sends users to the top of the document, starting with the "Skip to Main Content" link. 

Expected behavior would be to land on the submit button first. Then if there are radio buttons, land on those second (and in both cases, there should be clear visible indication of focus). 

With or without radio buttons, users should land back on the search toggle after they've cycled through the search fields, since that's where they started. Then they can continue on where they left off, or select the toggle to close the search.

**Comment by nwinkelbauer** [comment]
See commit ba522e5 for solution.
