### ISSUE TITLE
Big Hero template fields

### ISSUE THREAD

**Issue by jbleys** [uweb/uw-2014#141]
Hi,

The big hero template comes with fields for a banner text, and a button. It looks like these fields are only visible for folks with the administrator role. Would it be possible to make these fields editable for the Editor role as well?

The attached image shows the fields that my Editors cannot see.

![Big Hero - administartor only fields](https://user-images.githubusercontent.com/2615272/76367567-d2265280-6303-11ea-8177-5d9e004ce9ad.PNG)

Thanks,

JASPER BLEIJS, MSIM
web computing specialist
Department of Global Health | University of Washington 
Email: jbleys@uw.edu

**Comment by lcaple** [comment]
@jbleys Just got this resolved if you download the latest. Thank you for submitting the request!
