### ISSUE TITLE
Remove "Download" link from image attachment page

### ISSUE THREAD

**Issue by staceysowers** [uweb/uw-2014#148]
I've made several image galleries and have chosen to have each image link to an attachment page. Each attachment page shows the full-sized image with a caption. This is good. My issue is that a "Download" link automatically appears beneath the caption. I've attached a screenshot. Is there a way to remove this link from the template? I don't know CSS or how to create child-pages. The website isn't hosted by the department yet - it's currently on a private domain. I'm working on a prototype to submit a proposal to our IT department before launching it. Thanks for any ideas. 

![Attachment-page-captions](https://user-images.githubusercontent.com/67126218/85077496-4aa87500-b177-11ea-82ca-8f4ea62e6a64.jpg)

**Comment by lcaple** [comment]
Hi Stacy,

To make that change you will need to [create a child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) of uw-2014. It's pretty straight forward and you can simply override the [content-image.php](https://github.com/uweb/uw-2014/blob/master/content-image.php) file to remove the download link. This might be something whoever is setting up your site will need to do for you.

**Comment by staceysowers** [comment]
Thank you for your quick response and links, lcaple. I really appreciate it!

**Comment by staceysowers** [comment]
Hi Lauren, 

I made a child theme and found the content-image.php file. Do I just delete this part of the code and click Update? 

<div>

<a href="<?php echo wp_get_attachment_url(get_the_ID());?>" title="<?php the_title(); ?>" target="_blank" download="<?php the_title() ?>">Download</a>
 
</div>

**Comment by staceysowers** [comment]
Oops. I'm referring to this code. (I removed the carrots)

div
    a href="<?php echo wp_get_attachment_url(get_the_ID());?>" title="<?php the_title(); ?>" target="_blank" download="<?php the_title() ?>">Download

/div

**Comment by lcaple** [comment]
Yes those lines of code will remove it.

I'm going to close this out, but feel free to reopen if you have any other questions.
