### ISSUE TITLE
Remove H2 heading from site title

### ISSUE THREAD

**Issue by terrill** [uweb/uw-2014#15]
On most websites that use the Boundless theme, secondary pages have an h1 heading marking the main heading of the page, which is correct. This should be the **first** heading on the page. Currently the site title (element with class="uw-site-title") is tagged as h2, which breaks the outline of the page. This should be changed to a div element. 

For example, consider the Regents page: 
[http://www.washington.edu/regents/](http://www.washington.edu/regents/)

The site title is "Board of Regents" and is incorrectly tagged as h2.  The main heading is "UW Board of Regents" and is correctly tagged as H1. Removing the orphaned h2 results in a clean, logical outline that starts with an h1, thereby reducing cognitive load on screen reader users.

**Comment by nwinkelbauer** [comment]
Issue addressed in Commit b3cda9f
