### ISSUE TITLE
update to jQuery 3.x

### ISSUE THREAD

**Issue by jodytate** [uweb/uw-2014#162]
With the recent release of [WordPress 5.6](https://wordpress.org/news/2020/12/simone/), jQuery has been updated to the 3.x line. Does UW Marketing have plans to update the version of jQuery included with the theme? Currently it is set at 1.11.3.

**Comment by lcaple** [comment]
We're in the process of implementing jQuery 3.x (latest) in the next major update but it might require us to either refactor or retire some JS features.

**Comment by lcaple** [comment]
The jQuery version has been updated to match WordPress core in the [recent 3.0.0 release](https://github.com/uweb/uw-2014/releases/tag/3.0.0).
