### ISSUE TITLE
Missing documentation for Accordion shortcode URL detection

### ISSUE THREAD

**Issue by bonifacp** [uweb/uw-2014#163]
The theme documentation links to Nicolas Hoffmann's accordion documentation, but the UW implementation of URL matching includes the ability to target the button Id to open a section by default. This URL matching doesn't exist in Hoffman's version, and isn't documented anywhere (that I can find) outside the code itself.

**Comment by lcaple** [comment]
Can you elaborate on this? I am not sure what you mean by URL detection or URL matching.

**Comment by bonifacp** [comment]
Linking directly to an accordion section so it is open as the page loads, something like "washington.edu/site/page/#section1_2_3". This functionality exists in the code, but is not documented.

**Comment by lcaple** [comment]
I added a note about this to the documentation that will be included in the next release d7e1502ad4e023811f072751e79e56b3f0399655
