### ISSUE TITLE
Mobile search issue

### ISSUE THREAD

**Issue by levineaj** [uweb/uw-2014#166]
Hello. Just noticed an issue when using search dropdown located in the header while on a smaller (mobile) browser. Nothing happens when choosing "Current site" and clicking the search icon. Using Chrome on macOS desktop and Safari on iOS mobile.

Also, when on desktop, the toggle no longer works when you go from a mobile view to desktop view in your browser.

**Comment by lcaple** [comment]
This was fixed with b0718dad1a1401da8d6b5b5d75ec4d6ba251846d
