### ISSUE TITLE
Need better visible focus in banner

### ISSUE THREAD

**Issue by terrill** [uweb/uw-2014#17]
When a keyboard user tabs through the banner (audience-based navigation, search icon, and Quick Links button), the only visible indication that an item has focus is a change of color. This is not accessible to people who are unable to perceive color differences.  

There needs to be some additional indication of keyboard focus that's not dependent on color perception. For example, underlining the item that has focus would be effective.

**Comment by nwinkelbauer** [comment]
Issue addressed with commit cdd0909
