### ISSUE TITLE
Page Revisions cannot be viewed, restored

### ISSUE THREAD

**Issue by nambuben** [uweb/uw-2014#170]
## Issue

We cannot see page revisions or restore pages to previous versions.  The revision page (the one that shows the diff between content and is the confirmation page before an actual revision occurs) does load, but no content is displays apart from some minor WP GUI chrome.

The console on DevTools does show a JS error on the `admin.js` file in this theme.
`Uncaught TypeError: a(...).autocomplete is not a function`

## Reproduction Steps

*on /alumni*

* Navigate to the page with the title, `The free 509 Day tote promotion is closed`
* Click/tap on any revision in the "Revisions" Admin box

**Comment by lcaple** [comment]
HI Ben,

I cannot reproduce this error outside of the /alumni/ site with vanilla uw-2014. Do you have any admin.js running via your child theme?
