### ISSUE TITLE
Require PHP files in class file rather than functions.php

### ISSUE THREAD

**Issue by stvnspchr** [uweb/uw-2014#19]
Forgive me if there's a workaround for this. I'm not the most skilled PHP guy.

I'm extending your UW object in a child theme and implementing some features, dropping some, and including some of my own. While your use of the page templates meta box is really quite nice, we have a different need for it. Currently, I can only comment out line 17 of functions.php to get my functionality to work. I'd like to continue to get bug fixes etc from you guys. Could you move those require statements to inside your UW class file?

**Comment by nwinkelbauer** [comment]
Issue has been addressed in commit https://github.com/uweb/uw-2014/commit/9dd48ee4a4d98a47254477be8e9ea24efa3eae51 

Let us know if there are any further issues you run in to.

**Comment by stvnspchr** [comment]
Bingo! Thanks guys.
