### ISSUE TITLE
UW Mobile Menu Toggle button not displaying tab-navigation focus in Firefox

### ISSUE THREAD

**Issue by mattlam-uw** [uweb/uw-2014#21]
# Description

In Firefox, when navigating via TAB through UW-2014 themed page on small-device screen resolution, the mobile menu toggle button does not visibly display focus.
# Repro Steps
1. In Firefox (e.g. version 40.0.3), navigate to a UW-2014 themed page (e.g. http://www.washington.edu/brand/brand-guide/brand-pillars/)
2. Reduce horizontal window size of the page until the "dawgdrops" menu is replaced by the H1 page header and the mobile "MENU" toggle button
3. Refresh the page (F5)
4. Use the TAB key to navigate through the elements on the page to the breadcrumbs. 
5. As you TAB through the breadcrumbs, the "MENU" button should receive focus after the next-to-last breadcrumb. TAB to give the "MENU" button focus.
# Expected Result

The "MENU" button displays an outline or other indication that it currently has focus. This works with Chrome (version 45.0.2454.85 m) and IE (version 11.0.9600).
# Actual Result

In Firefox (version 40.0.3), the "MENU" button does not display any visual indication of having focus

**Comment by lcaple** [comment]
Fixed in #106 

Thank you for the detailed information on reproducing the issue.
