### ISSUE TITLE
Slideshow not displaying focus in IE or Chrome

### ISSUE THREAD

**Issue by mattlam-uw** [uweb/uw-2014#22]
# Description

Using keyboard (TAB) navigation on a page with a slideshow, the slideshow component shows no visual indication of receiving focus. This occurs only with IE and Chrome.
# Steps to Reproduce
1. Open a browser -- either Internet Explorer (version tested = 11.0.9600) or Chrome (version tested = 45.0.2454.99 m)
2. Navigate to a page that hosts the slideshow component (e.g. http://www.washington.edu/research/)
3. Use TAB to navigate through the page to the point where the slideshow component has focus
# Expected Result

The slideshow element visibly indicates focus to the user. In other words, the element itself or the navigation controls within the element are outlined or highlighted in some way.
# Actual Result

The slideshow element shows no visible indication of having focus.
# Additional Notes:

I logged this as follow-up to my comment on issue https://github.com/uweb/uw-2014/issues/13

**Comment by lcaple** [comment]
This issue was addressed in a previous update. Closing.
