### ISSUE TITLE
Compatibility with Wordpress - Which versions?

### ISSUE THREAD

**Issue by jkudebeh** [uweb/uw-2014#29]
What versions of Wordpress has this theme been tested against?
We are currently on 4.2.4 and are planning on upgrading to 4.4

thanks
Jim

**Comment by nwinkelbauer** [comment]
Hi, 

We are currently on 4.3.1
We have not talked about upgrading to 4.4 yet so I can not give you at a timeline. When we decide a timeline I will let you know. 


- Nick
