### ISSUE TITLE
CSS conflict with Formidable calendar UI

### ISSUE THREAD

**Issue by jkudebeh** [uweb/uw-2014#41]
The selected month and year text in the Formidable Plugin calendar widget are the same color as the background, see attached picture. The two top boxes that appear to be blank contain the month and year. When I activate the WordPress Twenty Fifteen theme, the month and year are visible.

![image](https://cloud.githubusercontent.com/assets/4480099/18934186/3b4de488-858d-11e6-9d0d-287c31c830f3.png)

**Comment by lcaple** [comment]
Unfortunately this is not a 3rd party plugin we're using so it'll be difficult to help you troubleshoot. I recommend creating a child theme to make the necessary modifications to the widget's CSS.

Closing.
