### ISSUE TITLE
CSS table.table-hover:hover conflicts with td.active:hover

### ISSUE THREAD

**Issue by jvogtuw** [uweb/uw-2014#49]
These two classes conflict causing a flicker on hover. In the following table, the first cell will flicker when the row is hovered over.

    <table class="table table-hover">
        <tbody>
            <tr>
                <td class="active">Auit Manro</td>
                <td>1</td>
                <td>Vestibulum id ligula porta felis euismod semper.</td>
            </tr>
        </tbody>
    </table>

**Comment by lcaple** [comment]
:hover state no longer present in the css for .table-hover class.

Closing.
