### ISSUE TITLE
nav#search-quicklinks wraps, needs min-width

### ISSUE THREAD

**Issue by jvogtuw** [uweb/uw-2014#50]
If the contents of the thinstrip links aren't long enough, the quicklinks button wraps under the search button when the page width is between 768 and 991px. This is only an issue if a child theme modifies the standard thinstrip link content. 
![image](https://cloud.githubusercontent.com/assets/15369656/21437830/f274878a-c83a-11e6-9d2b-ad199ef48039.png)

I propose adding `min-width: 233px;` to `.uw-thinstrip div.align-right #search-quicklinks`. Line 354 of uw.thinstrip.less.

**Comment by kilianf** [comment]
This has now been fixed in the latest UW-2014 commit. Thanks for the note.
