### ISSUE TITLE
Can't add persons to contact list

### ISSUE THREAD

**Issue by jbleys** [uweb/uw-2014#52]
Hi,

Issue: can't add persons using the contact list widget.

WP version: 4.7.2
uw-2014 version: latest master pull

Hoping you can confirm or recreate this issue.
Using the Contact list widget I run into a javascript ReferenceError which appears to be related to the uw.contact-widget.js script. The following error occurs when clicking the "Add person" button.

Chrome:
see attached log file
[staff.washington.edu-1487885738456.txt](https://github.com/uweb/uw-2014/files/797828/staff.washington.edu-1487885738456.txt)

Firefox:
13:39:57.552 ReferenceError: number is not defined 1 load-scripts.php:4:1
	anonymous https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:4:1
	m.template/c https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:141:15201
	Ha/< https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:3:20829
	.each https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:2:2879
	n.prototype.each https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:2:844
	Ha https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:3:20787
	.append https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:3:22791
	<anonymous> https://staff.washington.edu/jbleys/wordpress/wp-content/themes/uw-2014/assets/admin/js/widgets/uw.contact-widget.js:10:5
	n.event.dispatch https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:3:12392
	n.event.add/r.handle https://staff.washington.edu/jbleys/wordpress/wp-admin/load-scripts.php:3:9156

Kind regards,
Jasper Bleijs
jbleys@uw.edu

**Comment by jbleys** [comment]
Hi,
Just following up to see if the the log info provided is helpful or if you need any additional information?
Looking forward to any response.

Thanks,
Jasper

**Comment by DTaha** [comment]
I came across this as well and wanted to write an issue about it.

**Comment by lcaple** [comment]
Tracked the issue to changes in WordPress core javascript not working with our current code (written against a previous version of their libraries.) We're working on a bugfix that will hopefully be backwards compatible.

**Comment by lcaple** [comment]
Sorry for the delay. We fixed the issue in #104 and it's now added to the master branch. You can check the pull request page for information on the issue (if you're curious).
