### ISSUE TITLE
Moblie menu is displaying at widths > 768px.

### ISSUE THREAD

**Issue by NemesisVex** [uweb/uw-2014#62]
We're building a child theme based on the Boundless theme and pulled changes to uw-2014 within the past week.

After rebuilding our child theme CSS, I noticed the mobile menu is no longer hidden for desktop screens. I took a look at uw.mobile-menu.less and noticed lines 2 and 4 set "display: block" instead of "display: none". Is this correct? If so, then it must mean I'm missing a new component in my child theme, although I can't detect what.

Our child theme is not overriding any of the parent theme's mobile menu styles.

Thank you.

**Comment by lcaple** [comment]
I'm unable to replicate this issue with any of my child themes.

Feel free to reopen this issue if it's still occurring.
