### ISSUE TITLE
?q search parameter

### ISSUE THREAD

**Issue by Jorgu5** [uweb/uw-2014#86]
It looks like when i'm trying to implement GCS the same as it's done on the main UW website, it's not working properly. There are two different parameters used in the search on the top ?s and ?q. Since ?s is a standard WP search parameter, it's working just fine, but ?q does not redirect properly to the new template. I've noticed that on your main UW website you are using a plugin http://www.washington.edu/wp-content/plugins/uw-template-hierarchy/ which I believe is solving the problem, but I can't get it anywhere. 

Can you place some additional documentation on implementing GCS on this theme? This functionality has been hardcoded into theme with the UW links and it's not very easy to change it.

Thanks for the help on this one,
Best,
T.

**Comment by lcaple** [comment]
To get Google Custom Search implemented we created a search template override and included the GCS code and various GCS-specific CSS fixes. You can accomplish this by using the [template hierarchy built into WordPress](https://developer.wordpress.org/themes/basics/template-hierarchy/).

Essentially we created a page with the url slug search and a page template titled page-search.php. you should be able to do this directly from a theme or drop it into your uw-2014 directory, no plugin required.

**Comment by lcaple** [comment]
Closing this. If you have any more questions, feel free to reopen.
